#!/bin/bash
current_date_time=$(date)
rc_file=$1
tag="$2"
publickey=$3

required_servers=3

pvtkey="${publickey%.pub}"
current_dir="$(pwd)"
pvtkey_path="${current_dir}/${pvtkey}"

echo "$current_date_time Starting CleanUp with tag:$tag using $rc_file for credentials."
source $rc_file

# Define variables
name_of_the_network="${tag}_network"
name_of_the_subnet="${tag}_subnet"
name_of_the_keypair="${tag}_key"
name_of_the_router="${tag}_router"
name_of_the_securitygroup="${tag}_security_group"
haproxy_server1="${tag}_HAproxy1"
haproxy_server2="${tag}_HAproxy2"
bastion_server="${tag}_bastion"
server_name="${tag}_dev"
vport_name="${tag}_vport" #virtual ip port name

sshconfig="config"
hostsfile="hosts"
vport_file="vipaddr"
floating_ip1="floating_ip1"
floating_ip2="floating_ip2"

######                 Delete Network                ##########################
