#!/bin/bash

current_date_time=$(date)
rc_file=$1
tag_name=$2
publickey=$3
required_dev_servers=$(cat servers.conf)

echo "$current_date_time Starting deployment of $tag_name using $rc_file for credentials."
source $rc_file

# Define variables

name_of_the_network="$2_newnetwork"
name_of_the_subnet="$2_newsubnet"
name_of_the_keypair="$2_newkey"
name_of_the_router="$2_newrouter"
name_of_the_securitygroup="$2_security_group"
haproxy_server="$2_HAproxy"
haproxy_server2="$2_HAproxy2"
bastion_server="$2_bastion"
dev_server="$2_dev"
vip_port="$2_vip" #virtual ip port
sshconfig="config"
knownhosts="known_hosts"
hostsfile="hosts"
fip2="$(cat floating_ip2)"

# Get the list of servers matching the keyword
servers=$(openstack server list --name "$tag_name" -c ID -f value)
n=$(echo "$servers" | wc -l)
# Loop through each server and delete it
if [ -n "$servers" ]; then
  echo "$(date) Found $n server(s), deleting them"
  for server_id in $servers; do
    openstack server delete $server_id
  done
  echo "$(date) Deleted servers"
else
  echo "$(date) No servers exist to delete"
fi
