#!/bin/bash
current_date_time=$(date)
rc_file=$1
tag="$2"
publickey=$3

pvtkey="${publickey%.pub}"
current_dir="$(pwd)"
pvtkey_path="${current_dir}/${pvtkey}"

echo "$current_date_time Running Operation mode with tag:$tag using $rc_file credentials."
source $rc_file

# Define variables
name_of_the_network="${tag}_network"
name_of_the_subnet="${tag}_subnet"
name_of_the_keypair="${tag}_key"
name_of_the_router="${tag}_router"
name_of_the_securitygroup="${tag}_security_group"
haproxy_server1="${tag}_HAproxy1"
haproxy_server2="${tag}_HAproxy2"
bastion_server="${tag}_bastion"
server_name="${tag}_dev"
vport_name="${tag}_vport" #virtual ip port name

sshconfig="config"
hostsfile="hosts"
vport_file="vipaddr"

status_new=false

#########           CONFIGURING SERVERS             ######################

#1. BASTION SERVER
build_bastion() {
        #1      CREATE Bastion Server           ##
        existing_bastion=$(openstack server list --status ACTIVE --column Name -f value | grep "^$bastion_server$") #get exact match in search

        if echo "$existing_bastion" | grep -q "\b$bastion_server\b"; then
                        echo "$(date) Bastion: Already exists $bastion_server"
        else
                        bastion=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $bastion_server --key-name $name_of_the_keypair --flavor "1C-2GB-50GB" --network $name_of_the_network --security-group $name_of_the_securitygroup)
                        while true; do                                
                                        server_status=$(openstack server show "$bastion_server" -f value -c status)
                                        if [ "$server_status" == "ACTIVE" ]; then
                                                        break
                                        fi
                        done                        
                        echo "$(date) Bastion: Created server $bastion_server."
        fi

        # BASTION FIXED-IP
        bastion_ip=$(openstack server show $bastion_server -c addresses -f value | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}'| awk 'NR==1')
        echo "$(date) Bastion: Fixed IP:--$bastion_ip"

        #2.      existing FLOATING IPs           ##
        existing_bastion_fip=$(openstack floating ip list --fixed-ip-address $bastion_ip -c "Floating IP Address" -f value)
        
        if [[ -n "$existing_bastion_fip" ]]; then
                        ### 3.     GET: FLOATING IP 1           ###
                        echo "$(date) Bastion: Floating IP:$existing_bastion_fip found attached to Bastion IP:$bastion_ip"
                        fip1=$existing_bastion_fip   
                        echo $fip1 > floating_ip1 
        else
                        ### 3.     CREATE: FLOATING IP 1        ###
                        echo "$(date) Bastion: Assigning Floating IP for Bastion"
                        fip1=$(create_fip)
                        echo $fip1 > floating_ip1 # storing fip1 in a file "floating_ip1"

                        #1 ADD: Adding FLOATING IP (to the)---> BASTION Server.
                        update_fip1=$(openstack server add floating ip $bastion_server $fip1)           
        fi

        bastion_fip=$(openstack floating ip list --fixed-ip-address $bastion_ip -c "Floating IP Address" -f value)
                
        echo "$(date) Bastion: Configured with Fixed-IP:$bastion_ip & Floating-IP:$bastion_fip."
        echo ""
}

#2. HAPROXY SERVERS
build_HAproxy() {
        existing_haproxy1=$(openstack server list --status ACTIVE --column Name -f value | grep "^$haproxy_server1$") #get exact match in search
        if echo "$existing_haproxy1" | grep -q "\b$haproxy_server1\b"; then
                        echo "$(date) HAproxy: Already exists $haproxy_server1"
        else
                        haproxy1=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $haproxy_server1 --key-name $name_of_the_keypair --flavor "1C-2GB-50GB" --network $name_of_the_network --security-group $name_of_the_securitygroup)
                        while true; do                                
                                        server_status1=$(openstack server show "$haproxy_server1" -f value -c status)
                                        if [ "$server_status1" == "ACTIVE" ]; then
                                                        break
                                        fi
                        done  
                        echo "$(date) HAproxy: Created server $haproxy_server1"
                        status_new=true
        fi

        existing_haproxy2=$(openstack server list --status ACTIVE --column Name -f value | grep "^$haproxy_server2$") #get exact match in search
        if echo "$existing_haproxy2" | grep -q "\b$haproxy_server2\b"; then
                        echo "$(date) HAproxy: Already exists $haproxy_server2"
        else
                        haproxy2=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $haproxy_server2 --key-name $name_of_the_keypair --flavor "1C-2GB-50GB" --network $name_of_the_network --security-group $name_of_the_securitygroup)
                        while true; do                                
                                        server_status2=$(openstack server show "$haproxy_server2" -f value -c status)
                                        if [ "$server_status2" == "ACTIVE" ]; then
                                                        break
                                        fi
                        done  
                        echo "$(date) HAproxy: Created server $haproxy_server2."
                        status_new=true
        fi      
}

#3. VIRTUAL PORT
config_vport() {
        # HAproxy IPs
        ip_ha1=$(openstack server show $haproxy_server1 -c addresses -f value | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
        ip_ha2=$(openstack port list --server $haproxy_server2 -f json | jq -r '.[0]."Fixed IP Addresses"[0].ip_address')

        echo "$(date) HAproxy: Configured with Fixed IPs: $ip_ha1 and $ip_ha2" 

        #1.      create VIRTUAL PORT            ##
        existing_vport=$(openstack port list | grep "$vport_name" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
        if [[ -n "$existing_vport" ]]; then
                        echo "$(date) Virtual Port: Already exists $vport_name"
        else
                        new_virtualport=$(openstack port create --network "$name_of_the_network" --fixed-ip subnet="$name_of_the_subnet" --no-security-group "$vport_name")
                        echo "$(date) Virtual Port: Created port $vport_name"
                        status_new=true
        fi

        # IP addr Virtual Port
        ip_vport=$(openstack port show $vport_name --format json | jq -r '.fixed_ips[0].ip_address')
        echo "$ip_vport" >> $vport_file # keeping V-Port FIXED IP address in a file "vipaddr"  

        #2.      existing FLOATING IPs           ##

        existing_vport_fip=$(openstack floating ip list --fixed-ip-address $ip_vport -c "Floating IP Address" -f value)
        if [[ -n "$existing_vport_fip" ]]; then
                        #echo "$(date) Floating IPs $existing_vport_fip are available"

                        ### 3.     GET: FLOATING IP 2           ###
                        echo "$(date) Virtual Port: Floating IP:$existing_vport_fip found attached to VPort IP: $ip_vport"
                        fip2=$existing_vport_fip   
                        echo $fip2 > floating_ip2 
        else
                        ### 3.     CREATE: FLOATING IP 2        ###
                        echo "$(date) Virtual Port: Assigning Floating IP for HAproxy Servers"
                        fip2=$(create_fip)
                        echo $fip2 > floating_ip2 # storing fip2 in a file "floating_ip2"

                        #1 SET: Attaching VIRTUAL PORT (to the)---> FLOATING IP.
                        update_fip2=$(openstack floating ip set --port $vport_name $fip2)

                        status_new=true           
        fi

        if [[ "$status_new" == true ]]; then
                        echo "$(date) Virtual Port: Configuring"

                        status_new=false

                        #  EMPTY VIRTUAL PORT allowed addresses if exists   
                        allowed_vport=$(openstack port show $vport_name --format json | jq -r '.allowed_address_pairs[0].ip_address')

                        if [[ -n "$allowed_vport" ]]; then
                                        empty_vport=$(openstack port set --no-allowed-address $vport_name)
                        fi

                        #2 SET: Update/Attaching FLOATING IP (to the)---> VIRTUAL PORT. 
                        update_vport=$(openstack port set --allowed-address ip-address="$fip2" $vport_name)

                        #3 SET: Attaching the HAproxy Port IPs (to the)---> VIRTUAL PORT.
                        up_vport_ha1=$(openstack port set --allowed-address ip-address=$ip_ha1 $vport_name)
                        up_vport_ha2=$(openstack port set --allowed-address ip-address=$ip_ha2 $vport_name)

                        # HAproxy PORT IDs
                        portid_ha1=$(openstack port list --server $haproxy_server1 -c ID -f value)
                        portid_ha2=$(openstack port list --server $haproxy_server2 -c ID -f value)
                        
                        # HAproxy FIXED IPs
                        allowed_ha1=$(openstack port show $portid_ha1 --format json | jq -r '.allowed_address_pairs[0].ip_address')
                        allowed_ha2=$(openstack port show $portid_ha2 --format json | jq -r '.allowed_address_pairs[0].ip_address')

                        #4 SET: Attaching VIRTUAL PORT *FIXED-IP* (to the)---> HAPROXY SERVERs-IDs.
                        if [[ -n "$allowed_ha1" ]]; then
                                        empty_ha1=$(openstack port set --no-allowed-address $portid_ha1)
                        fi        
                        update_ha1=$(openstack port set --allowed-address ip-address=$ip_vport $portid_ha1)

                        if [[ -n "$allowed_ha2" ]]; then
                                        empty_ha2=$(openstack port set --no-allowed-address $portid_ha2)
                        fi
                        update_ha2=$(openstack port set --allowed-address ip-address=$ip_vport $portid_ha2)
        else
                        echo "$(date) Virtual Port: already configured"
        fi

        haproxy_fip=$(openstack floating ip list --fixed-ip-address $ip_vport -c "Floating IP Address" -f value)
        echo "$(date) Virtual Port: Configured with HAproxy Servers -- FLOATING IP:$haproxy_fip"
        echo ""
}

create_fip() {
        local floating_ip=""

        unassigned_ips=$(openstack floating ip list --status DOWN -f value -c "Floating IP Address")
        if [[ -n "$unassigned_ips" ]]; then
                        floating_ip=$(echo "$unassigned_ips" | awk 'NR==1')            
        else
                        floating_ip=$(openstack floating ip create ext-net -f json | jq -r '.floating_ip_address')
        fi
        echo "$floating_ip"
}

#########           DEV SERVERS SETUP             ###################
build_servers() {

        local required_servers=$1
        local server_name="$2"

        local list_servers=$(openstack server list -c Name -f value | grep "$server_name")
        local active_servers=$(openstack server list --status ACTIVE -f value -c Name | grep "$server_name")

        local servers=($list_servers)
        local list_count=${#servers[@]}

        local up_servers=($active_servers)
        local up_count=${#up_servers[@]}

        local sequence=1
        local count=1

        echo "$(date) Dev Servers:req: $required_servers"
        
        for item in ${servers[@]}; do
                echo "$(date) Dev Servers: LIST  :$list_count::$item"
        done

        for item in ${up_servers[@]}; do
                echo "$(date) Dev Servers: ACTIVE:$up_count::$item"
        done

        
        while true; do
                if (( sequence > required_servers )); then
                                break
                fi

                new_server_name="${server_name}${count}"
                
                # if the new server exist in servers list
                if exists_in_list "${servers[@]}" " " "$new_server_name"; then

                                # if the new server exist in active servers 
                                if exists_in_list "${up_servers[@]}" " " "$new_server_name"; then
                                                echo "$(date) Dev Servers: Existing active server $new_server_name."
                                                ((sequence++))
                                else
                                                echo "$(date) Dev Servers: INACTIVE server $new_server_name."
                                fi
                else
                                server_output=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64"  $new_server_name --key-name "$name_of_the_keypair" --flavor "1C-2GB-50GB" --network $name_of_the_network --security-group $name_of_the_securitygroup)
                                while true; do                                
                                        server_status=$(openstack server show "$new_server_name" -f value -c status)
                                        if [ "$server_status" == "ACTIVE" ]; then
                                                        break
                                        fi
                                done
                                ((sequence++))
                                echo "$(date) Dev Servers: Created server $new_server_name."                                
                fi
                ((count++))                
        done
}
